SELECT TO_CHAR(SALES_DATE,'YYYY') AS YEAR
      ,TO_CHAR(SALES_DATE,'MM') AS MONTH
      ,UI.GENDER AS GENDER
      ,COUNT(DISTINCT UI.USER_ID) AS USERS
FROM ONLINE_SALE OS
LEFT JOIN USER_INFO UI 
       ON OS.USER_ID = UI.USER_ID
WHERE UI.GENDER IS NOT NULL
GROUP BY TO_CHAR(SALES_DATE,'YYYY') ,TO_CHAR(SALES_DATE,'MM') ,UI.GENDER
ORDER BY YEAR ,MONTH ,GENDER