SELECT MONTH
      ,CAR_ID
      ,RECORDS
FROM (
      SELECT DISTINCT TO_CHAR(CRCRH.START_DATE, 'MM') AS MONTH,
                      CRCRH.CAR_ID,
                      COUNT(*) OVER(PARTITION BY TO_CHAR(CRCRH.START_DATE, 'MM'), CRCRH.CAR_ID) AS RECORDS,
                      COUNT(*) OVER(PARTITION BY CRCRH.CAR_ID) AS FIVE_CHECK
      FROM  CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH
      WHERE TO_CHAR(CRCRH.START_DATE, 'YYYY-MM-DD') BETWEEN '2022-08-01' AND '2022-10-31'
)
WHERE FIVE_CHECK >= 5 
ORDER BY MONTH, CAR_ID DESC