SELECT B.HOUR, 
       NVL(A.COUNT,0) AS COUNT
FROM (
    SELECT TO_CHAR(DATETIME, 'HH24') AS HOUR, 
           COUNT(*) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY TO_CHAR(DATETIME, 'HH24')
) A
RIGHT JOIN (
        SELECT (LEVEL-1) AS HOUR
        FROM DUAL
        CONNECT BY LEVEL <= 24
) B ON A.HOUR = B.HOUR
ORDER BY B.HOUR