SELECT A.CATEGORY
      ,SUM(B.SALES) AS TOTAL_SALES
FROM BOOK A
LEFT JOIN BOOK_SALES B
       ON A.BOOK_ID = B.BOOK_ID
WHERE SUBSTR(TO_CHAR(B.SALES_DATE,'YYYYMMDD'),0,6) = '202201'
GROUP BY A.CATEGORY
ORDER BY A.CATEGORY