-- 2021년에 가입한 전체 회원수
-- SELECT COUNT(*)
-- FROM USER_INFO UI
-- WHERE SUBSTR(TO_CHAR(UI.JOINED,'YYYY-MM-DD'),0,4) = '2021'

-- 2021년에 가입한 전체 회원들 중 상품을 구매한 회원 수
SELECT TO_CHAR(OS.SALES_DATE,'YYYY') AS YEAR
      ,TO_CHAR(OS.SALES_DATE,'MM') AS MONTH
      ,COUNT(DISTINCT UI.USER_ID) AS PUCHASED_USERS
      ,ROUND(COUNT(DISTINCT UI.USER_ID) / (SELECT COUNT(UI_SUB.USER_ID)
                                       FROM USER_INFO UI_SUB
                                      WHERE SUBSTR(TO_CHAR(UI_SUB.JOINED,'YYYY-MM-DD'),0,4) = '2021'
                                    ),1) AS PUCHASED_RATIO
FROM ONLINE_SALE OS
LEFT JOIN USER_INFO UI
       ON OS.USER_ID = UI.USER_ID
WHERE SUBSTR(TO_CHAR(UI.JOINED,'YYYY-MM-DD'),0,4) = '2021'
GROUP BY TO_CHAR(OS.SALES_DATE,'YYYY'), TO_CHAR(OS.SALES_DATE,'MM')
ORDER BY YEAR, MONTH