SELECT B.PRODUCT_ID
      ,B.PRODUCT_NAME
      ,A.TOTAL_SALES
FROM (
        SELECT FP.PRODUCT_ID
               ,SUM(FP.PRICE * FO.AMOUNT) AS TOTAL_SALES
        FROM FOOD_PRODUCT FP
        LEFT JOIN FOOD_ORDER FO
               ON FP.PRODUCT_ID = FO.PRODUCT_ID
        WHERE SUBSTR(TO_CHAR(FO.PRODUCE_DATE,'YYYYMMDD'),0,6) = '202205'
        GROUP BY FP.PRODUCT_ID
) A
LEFT JOIN FOOD_PRODUCT B
       ON A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY A.TOTAL_SALES DESC, B.PRODUCT_ID