\SELECT A.HISTORY_ID
      ,ROUND((A.DAILY_FEE - A.DAILY_FEE * NVL(B.DISCOUNT_RATE,0) / 100) * A.DAY,0) AS FEE
FROM (
        SELECT CRCRH.HISTORY_ID
              ,CRCRH.CAR_ID
              ,CRCC.CAR_TYPE
              ,CRCC.DAILY_FEE
              ,CASE WHEN (CRCRH.END_DATE - CRCRH.START_DATE + 1) >= 90 THEN '90일 이상'
                    WHEN (CRCRH.END_DATE - CRCRH.START_DATE + 1) >= 30 THEN '30일 이상'
                    WHEN (CRCRH.END_DATE - CRCRH.START_DATE + 1) >= 7 THEN '7일 이상'
               ELSE '7일 미만'
               END AS DURATION_TYPE
              ,CRCRH.END_DATE - CRCRH.START_DATE + 1 AS DAY
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH
        LEFT JOIN CAR_RENTAL_COMPANY_CAR CRCC
               ON CRCRH.CAR_ID = CRCC.CAR_ID
      ) A
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B
       ON A.DURATION_TYPE = B.DURATION_TYPE
      AND A.CAR_TYPE = B.CAR_TYPE
WHERE A.CAR_TYPE = '트럭'
ORDER BY FEE DESC, A.HISTORY_ID DESC
