SELECT CRCRH.CAR_ID
      ,ROUND(AVG(CRCRH.END_DATE - CRCRH.START_DATE + 1),1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH
GROUP BY CRCRH.CAR_ID
HAVING AVG(CRCRH.END_DATE - CRCRH.START_DATE + 1) >= 7
ORDER BY AVERAGE_DURATION DESC, CRCRH.CAR_ID DESC