SELECT A.SALES_DATE
      ,A.PRODUCT_ID
      ,A.USER_ID
      ,A.SALES_AMOUNT
FROM
(
    -- 온라인
    SELECT ONS.USER_ID
          ,ONS.PRODUCT_ID
          ,ONS.SALES_AMOUNT
          ,TO_CHAR(ONS.SALES_DATE,'YYYY-MM-DD') AS SALES_DATE
    FROM ONLINE_SALE ONS
    WHERE SUBSTR(TO_CHAR(ONS.SALES_DATE,'YYYYMMDD'),0,6) = '202203'

    UNION ALL
    -- 오프라인
    SELECT NULL AS USER_ID
          ,OFFS.PRODUCT_ID
          ,OFFS.SALES_AMOUNT
          ,TO_CHAR(OFFS.SALES_DATE ,'YYYY-MM-DD') AS SALES_DATE
    FROM OFFLINE_SALE OFFS
    WHERE SUBSTR(TO_CHAR(OFFS.SALES_DATE ,'YYYYMMDD'),0,6) = '202203'
) A
ORDER BY A.SALES_DATE, A.PRODUCT_ID, A.USER_ID